name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: 1. Instalar dependencias
        run: npm ci

      - name: 2. Compilar el proyecto
        run: npm run build

      - name: 3. Ejecutar los tests unitarios con Vitest
        run: npm test -- --run

      - name: 4. Generar el reporte de cobertura
        run: npm run test:coverage

      - name: 5. Ejecutar análisis estático con ESLint
        run: npm run lint

      - name: 6. Instalar dependencias del sistema y navegadores de Playwright
        run: npx playwright install --with-deps

      - name: 7. Ejecutar los tests de aceptación con Playwright
        run: npm run at

      - name: Guardar reporte de Playwright si ocurre un fallo
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30